vim.opt.number = true
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.showmode = false
vim.opt.visualbell = true
vim.opt.wrap = false
vim.opt.cursorline = true
vim.opt.mouse = "a"
vim.opt.termguicolors = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.updatetime = 100
vim.opt.encoding = "utf-8"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.hls = false
vim.opt.ic = false

-- rust opt
vim.g.rustfmt_autosave = true
